PYTHONPATH:
    - $PROJECT_ROOT/apps
DEBUG: False
SECRET_KEY_FILE: $PROJECT_ROOT/SECRET_KEY
ROOT_URLCONF: urls
DATABASES:
    default:
        ENGINE: django.db.backends.sqlite3
        NAME: db/dev.db
TIME_ZONE: America/Detroit
SITE_ID: 1
USE_I18N: False
# USE_L10N: False
STATIC_ROOT: $PROJECT_ROOT/staticroot
STATIC_URL: /static/
ADMIN_MEDIA_PREFIX: /static/admin/
SHORT_DATE_FORMAT: Y-m-d
STATICFILES_DIRS:
    - $PROJECT_ROOT/static
STATICFILES_FINDERS:
    - django.contrib.staticfiles.finders.FileSystemFinder
    - django.contrib.staticfiles.finders.AppDirectoriesFinder
TEMPLATE_DIRS:
    - $PROJECT_ROOT/apps
    - $PROJECT_ROOT/templates
TEMPLATE_LOADERS:
    - djaml.filesystem
    - django.template.loaders.filesystem.Loader
    - django.template.loaders.app_directories.Loader
INSTALLED_APPS:
    - django_extensions
    - django.contrib.auth
    - django.contrib.contenttypes
    - django.contrib.sessions
    - django.contrib.sites
    - django.contrib.messages
    - django.contrib.staticfiles
    - django.contrib.admin
    - south
    - tastypie
    - blog


